### ISSUE TITLE
ArgumentOutOfRangeException when saying ">?" in chat

### ISSUE THREAD

**Issue by codehexen** [aura-project/aura#103]
```
[Error] - There has been a problem while handling '526C'.
[Exception] - System.ArgumentOutOfRangeException: Index was out of range. Must b
e non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Aura.Channel.Util.GmCommandManager.Process(ChannelClient client, Creature creature, String message) in g:\aura\src\ChannelServer\Util\GmCommands.cs:line 167
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.Chat(ChannelClient client, Packet packet) in g:\aura\src\ChannelServer\Network\Handlers\Chat.cs:line 25
   at Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet) in g:\aura\src\Shared\Network\PacketHandlerManager.cs:line 72
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.Handle(ChannelClient client, Packet packet) in g:\aura\src\ChannelServer\Network\Handlers\Base.cs:line 56
   at Aura.Shared.Network.DefaultServer`1.HandleBuffer(TClient client, Byte[] buffer) in g:\aura\src\Shared\Network\DefaultServer.cs:line 66
```

**Comment by codehexen** [comment]
Update: it doesn't just happen with '?', it's with all non-alphanumeric characters (except '>', due to it being handled directly)
