### ISSUE TITLE
Windmill Issue

### ISSUE THREAD

**Issue by UnknownVoid** [aura-project/aura#131]
````
3/7/2015 2:22:10 AM [Error] - There has been a problem while handling '6986'.
3/7/2015 2:22:10 AM [Exception] - System.Exception: Expected Int, got None.
   at Aura.Shared.Network.Packet.GetInt() in Shared\Network\Packet.cs:line 311
   at Aura.Channel.Skills.Combat.Windmill.Use(Creature attacker, Skill skill, Packet packet) in \ChannelServer\Skills\Combat\Windmill.cs:line 97
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.SkillUse(ChannelClient client, Packet packet) in ChannelServer\Network\Handlers\Skills.cs:line 346
   at Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet) in Shared\Network\PacketHandlerManager.cs:line 72
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.Handle(ChannelClient client, Packet packet) in ChannelServer\Network\Handlers\Base.cs:line 56
   at Aura.Shared.Network.DefaultServer`1.HandleBuffer(TClient client, Byte[] buffer) in Shared\Network\DefaultServer.cs:line 66
````

**Comment by exectails** [comment]
Did you do anything special?

**Comment by UnknownVoid** [comment]
this also happens with final hit, the issue seems to happen when your outside of attack range and it tries to execute the skill on the target. ^^

**Comment by exectails** [comment]
I can't reproduce this, when I use FH out of range the character runs into range, when I use WM *on* a monster I get an "Unimplemented" message.

I know what's causing the error, the packet structure is different in that specific situation you've created somehow, but I'd like to know what situation that is exactly, so we know what to look out for.

**Comment by exectails** [comment]
I've watched your video but I'm still unable to reproduce this o.o

**Comment by UnknownVoid** [comment]
it's strange, i did delete my cache. so not sure, i just know when this issue happens your frozen for a few seconds and can't move o-o

**Comment by UnknownVoid** [comment]
try to move during a final hit attack. it will produce 791B handler errors at least and eventually. CombatAttack: skill handler or interface for final hit error. ^^

**Comment by exectails** [comment]
>it will produce 791B handler errors

That's not an error, it's an unimplemented packet, and it's not the issue o.o
