### ISSUE TITLE
Mob Killing issue

### ISSUE THREAD

**Issue by UnknownVoid** [aura-project/aura#150]
12/23/2015 12:58:42 AM [Error] - There has been a problem while handling '6986', 'SkillUse'.
12/23/2015 12:58:42 AM [Exception] - System.Exception: No monster data found.
   at Aura.Channel.World.Dungeons.Puzzles.PuzzlePlace.SpawnSingleMob(String mobGroupName, String mobToSpawn, Placement placement) in D:\Source Code\aura-master\aura rebirth - Copy\src\ChannelServer\World\Dungeons\Puzzles\PuzzlePlace.cs:line 396
   at KeychestMonsterScript.OnMonsterDead(Puzzle puzzle, MonsterGroup group)
   at Aura.Channel.World.Dungeons.Puzzles.MonsterGroup.OnDeath(Creature creature, Creature killer) in D:\Source Code\aura-master\aura rebirth - Copy\src\ChannelServer\World\Dungeons\Puzzles\MonsterGroup.cs:line 117
   at Aura.Channel.World.EventHandlerExtensions.Raise[T1,T2](Action`2 handler, T1 args1, T2 args2) in D:\Source Code\aura-master\aura rebirth - Copy\src\ChannelServer\World\EventManager.cs:line 240
   at Aura.Channel.World.Entities.Creature.Kill(Creature killer) in D:\Source Code\aura-master\aura rebirth - Copy\src\ChannelServer\World\Entities\Creature.cs:line 1761
   at Aura.Channel.World.Entities.NPC.Kill(Creature killer) in D:\Source Code\aura-master\aura rebirth - Copy\src\ChannelServer\World\Entities\NPC.cs:line 290
   at Aura.Channel.World.Entities.Creature.TakeDamage(Single damage, Creature from) in D:\Source Code\aura-master\aura rebirth - Copy\src\ChannelServer\World\Entities\Creature.cs:line 1731
   at Aura.Channel.Skills.Combat.CombatMastery.Use(Creature attacker, Skill skill, Int64 targetEntityId) in D:\Source Code\aura-master\aura rebirth - Copy\src\ChannelServer\Skills\Combat\CombatMastery.cs:line 123
   at Aura.Channel.Skills.Combat.FinalHit.Use(Creature creature, Skill skill, Packet packet) in D:\Source Code\aura-master\aura rebirth - Copy\src\ChannelServer\Skills\Combat\FinalHit.cs:line 149
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.SkillUse(ChannelClient client, Packet packet) in D:\Source Code\aura-master\aura rebirth - Copy\src\ChannelServer\Network\Handlers\Skills.cs:line 391
   at Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet) in D:\Source Code\aura-master\aura rebirth - Copy\src\Shared\Network\PacketHandlerManager.cs:line 72
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.Handle(ChannelClient client, Packet packet) in D:\Source Code\aura-master\aura rebirth - Copy\src\ChannelServer\Network\Handlers\Base.cs:line 58
   at Aura.Shared.Network.DefaultServer`1.HandleBuffer(TClient client, Byte[] buffer) in D:\Source Code\aura-master\aura rebirth - Copy\src\Shared\Network\DefaultServer.cs:line 67

How to reproduce

#Keep the skill loaded and attack enemies into you run into this error (Preferably inside a dungeon)

**Comment by exectails** [comment]
What was the actual error? You only copied the stack trace.

**Comment by UnknownVoid** [comment]
the error itself is just 12/23/2015 12:58:42 AM [Error] - There has been a problem while handling '6986', 'SkillUse'.

There is no details in the log about what exactly what went wrong with this skill other then it had a error..

to reproduce Just run the Holiday run with final hit on, it will happen after around 5-10 rooms in. ^^

**Comment by exectails** [comment]
Could you copy the entire error+stack trace please, I'm missing the exception message.

I tried to reproduce it already, even though not in a dungeon.

**Comment by UnknownVoid** [comment]
Alright updated first post, it seems ether a issue with keys spawning inside the dungeon when using this skill or it's a issue with the skill itself. (stack trace points in soo many directions).

**Comment by exectails** [comment]
It's completely unrelated to keys or skills. I'll look into it in a bit, to confirm my suspicion.

**Comment by exectails** [comment]
Closed, since this is not a core issue. The problem is your Christmas Math dungeon. You're only specifying 2 mob groups for several scripts that need 3. Like keychest_monster2 for example. The script then tries to use that missing mob data, which throws an exception:

```
System.Exception: No monster data found.
```

which you can see above, at the beginning of the stack trace. Btw, a stack trace doesn't point in several directions, it simply tells you which methods the program called to get to the exception. In the above trace you can see how a monster was killed, it went through the OnDeath event, it tried to spawn the next wave, and then it hit the above exception. It couldn't find the monster data, because you didn't define it.
