### ISSUE TITLE
Packet Error

### ISSUE THREAD

**Issue by ImaBrokeDude** [aura-project/aura#173]
I am completely at a loss as to how this could have occurred but I did experience this and was hoping there was something I could do to help with preventing this kind of thing.

```
6/24/2015 8:24:18 PM [Error] - There has been a problem while handling 'F213303'.
6/24/2015 8:24:18 PM [Exception] - System.Exception: Expected Int, got 216.
   at Aura.Mabi.Network.Packet.GetInt() in c:\Users\ServerAdmin\Desktop\MabiBroke\src\Mabi\Network\Packet.cs:line 311
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.Run(ChannelClient client, Packet packet) in c:\Users\ServerAdmin\Desktop\MabiBroke\src\ChannelServer\Network\Handlers\Movement.cs:line 35
   at Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet) in c:\Users\ServerAdmin\Desktop\MabiBroke\src\Shared\Network\PacketHandlerManager.cs:line 73
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.Handle(ChannelClient client, Packet packet) in c:\Users\ServerAdmin\Desktop\MabiBroke\src\ChannelServer\Network\Handlers\Base.cs:line 58
   at Aura.Shared.Network.DefaultServer`1.HandleBuffer(TClient client, Byte[] buffer) in c:\Users\ServerAdmin\Desktop\MabiBroke\src\Shared\Network\DefaultServer.cs:line 61
6/24/2015 8:24:18 PM [Error] - While receiving data from 'XXX.XXX.50.241:55499'.
6/24/2015 8:24:18 PM [Exception] - System.Exception: Buffer too small to receive full packet (801435111).
   at Aura.Shared.Network.BaseServer`1.OnReceive(IAsyncResult result) in c:\Users\ServerAdmin\Desktop\MabiBroke\src\Shared\Network\BaseServer.cs:line 181
6/24/2015 8:24:18 PM [Error] - Unable to send packet to 'XXX.XXX.50.241:55499'. (Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.)
```

**Comment by xKamuna** [comment]
It looks like they may have added new data to the movement on the client.  I haven't updated yet, so I can't check that out yet.

**Comment by Pikachews** [comment]
No, that doesn't seem to be the problem. If they added packet data, you would get a valid data type in the error. Also, that would have been noticed almost immediately, since that is one of the first things you would do when you log in.
He's going to need to give up a lot more information than just that.

**Comment by xKamuna** [comment]
Ah, you're right.  I forgot that 216 was the data type, not the number.  That's strange.

**Comment by exectails** [comment]
Are you sure this happened on a clean version of Aura?

**Comment by ImaBrokeDude** [comment]
Squeaky clean, this happen right after I messaged you about breaking my server broadcasting, so I had to revert to a clean source I haven't had the time to add any of my scripts to it yet.

This particular person said they were attempting to log in for the first time and it failed (timeout, which is strange) but then she had another user log in for them which fixed the issue (stranger) and as soon as they got on and started walking they were booted do to the above exception (...).

**Comment by exectails** [comment]
I can't reproduce this, however, I did find a bug in the Warp code, you basically couldn't do anything after the Tin cutscene, because the screen stayed black. So thanks for that =P

The problem here is not with a packet, or reading a wrong value, as Pika already mentioned. If you get a completely invalid packet element type something in the packet initialization or parsing must be wrong.

Right now I have no idea how this could happen. We cut off the checksum, there should be nothing after the values. So the packet couldn't have simply been empty. It can't be still encrypted either, because the op wouldn't be correct then. I'd need to see the buffer to debug this =/

**Comment by ImaBrokeDude** [comment]
Is there any ways I could pull that? The server is still running from that particular session. Also can we add biffer dumps for packet error like that? Would be a nice debug feature xD.

Sent from Yahoo Mail on Android

**Comment by exectails** [comment]
I guess we could add a debug output for it. And no, you can't pull that information anymore, the buffer is long gone.

**Comment by Xcelled** [comment]
I see that "buffer too small" message. Could this, in anyway, be related to the Morrighan bug  that plagued Rydian?
