### ISSUE TITLE
Full Inventory Gold Bag Bug Number Two

### ISSUE THREAD

**Issue by xKamuna** [aura-project/aura#180]
From the forum:

>I got this error when switching a Big Gold Pouch from the temp inventory with an Arrow from the inventory, with my inventory being full.  I didn't feel like this would require a new topic, but I didn't want to double post, either.
 ```
[Error] - There has been a problem while handling '59D8'.
[Exception] - System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Aura.Channel.World.Inventory.InventoryPocketNormal.TryAdd(Item newItem, Byte targetX, Byte targetY, Item& collidingItem) in C:\Aura\aura\src\ChannelServer\World\Inventory\InventoryPockets.cs:line 184
   at Aura.Channel.World.Inventory.CreatureInventory.Move(Item item, Pocket target, Byte targetX, Byte targetY) in C:\Aura\aura\src\ChannelServer\World\Inventory\CreatureInventory.cs:line 504
 at Aura.Channel.Network.Handlers.ChannelServerHandlers.ItemMove(ChannelClient client, Packet packet) in C:\Aura\aura\src\ChannelServer\Network\Handlers\Items.cs:line 74
   at Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet) in C:\Aura\aura\src\Shared\Network\PacketHandlerManager.cs:line 73
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.Handle(ChannelClient client, Packet packet) in C:\Aura\aura\src\ChannelServer\Network\Handlers\Base.cs
:line 58
   at Aura.Shared.Network.DefaultServer`1.HandleBuffer(TClient client, Byte[] buffer) in C:\Aura\aura\src\Shared\Network\DefaultServer.cs:line 67
```
After logging out and logging back in, the Arrow is gone, but not the gold bag, it seems.  However, it seems like a space from my inventory is missing where two piles of gold should have been, but maybe I'm just going crazy.
EDIT:  I can confirm that this happens WHENEVER I do so, vice versa too, but only when I have a full inventory...  I might look into this later if someone doesn't get to it before me.  I must note that my CreatureInventory is edited (but that line isn't), so line 504 is this line:
```
if (!_pockets[target].TryAdd(item, targetX, targetY, out collidingItem))
```

**Comment by exectails** [comment]
You won't get to the core of the problem looking at that stack trace. The problem lies somewhere in the pocket code, where the pouch doesn't get switched with the arrow properly for some reason. Or rather, it is, but the client isn't told about it, or both. Then you try to move again, and that messes everything up and causes that exception.

I assume this has something to do with sacs, since apparently you can't switch a pouch with any (?) item, full inventory or not.

**Comment by exectails** [comment]
I think I got it =/ The inventory really needs a rewrite. This is so frustrating, you start coding with certain requirements in mind, 2 days later new ones come around, or you forgot something, and that breaks everything. This bug is new, switching sacs did work before, no idea what even caused this now o,o
