### ISSUE TITLE
Error in 4E34 | ChannelGetList

### ISSUE THREAD

**Issue by ImaBrokeDude** [aura-project/aura#193]
I have an errorwith channels that is cause people to have to log off. I am not quite sure why but if anything I can think would help, max users is set to 100, with 3 users on at the time.

```
1/5/2016 9:50:34 PM [Error] - There has been a problem while handling '4E34', 'GetChannelList'.
1/5/2016 9:50:34 PM [Exception] - System.DivideByZeroException: Attempted to divide by zero.
   at Aura.Shared.Network.ChannelInfo.get_Stress() in C:\Aura\aura\src\Shared\Network\ServerInfo.cs:line 62
   at Aura.Shared.Network.Sending.Helpers.ServerInfoHelper.AddChannelInfo(Packet packet, ChannelInfo channel, ServerInfoType type) in C:\Aura\aura\src\Shared\Network\Sending\Helpers\ServerInfoHelper.cs:line 52
   at Aura.Shared.Network.Sending.Helpers.ServerInfoHelper.AddServerInfo(Packet packet, ServerInfo server, ServerInfoType type) in C:\Aura\aura\src\Shared\Network\Sending\Helpers\ServerInfoHelper.cs:line 41
   at Aura.Channel.Network.Sending.Send.GetChannelListR(ChannelClient client, ServerInfo server) in C:\Aura\aura\src\ChannelServer\Network\Sending\Send.LogInOut.cs:line 117
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.GetChannelList(ChannelClient client, Packet packet) in C:\Aura\aura\src\ChannelServer\Network\Handlers\LogInOut.cs:line 337
   at Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet) in C:\Aura\aura\src\Shared\Network\PacketHandlerManager.cs:line 72
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.Handle(ChannelClient client, Packet packet) in C:\Aura\aura\src\ChannelServer\Network\Handlers\Base.cs:line 58
   at Aura.Shared.Network.DefaultServer`1.HandleBuffer(TClient client, Byte[] buffer) in C:\Aura\aura\src\Shared\Network\DefaultServer.cs:line 61
1/5/2016 9:50:39 PM [Info] - 'yumiser' is closing the connection. Saving...
1/5/2016 9:50:39 PM [Info] - Connection closed from 'XXX.XXX.XXX:52666.
1/5/2016 9:50:44 PM [Info] - Connection established from 'XXX.XXX.XXX:52851.
```

**Comment by exectails** [comment]
>max users is set to 100

Are you *really* sure about that?
>DivideByZeroException

The exception implies that MaxUsers is 0.

**Comment by ImaBrokeDude** [comment]
Very sure

http://i.imgur.com/F7tHQr0.png

**Comment by exectails** [comment]
Actually, you can't even set it to 0 anymore, that was fixed recently. Did you change anything in the source?

**Comment by ImaBrokeDude** [comment]
Sorry again, as you mention that, yeah my aura is out of date, forgot to pull the last changes before recompiling XD. Gonna test this now.

**Comment by exectails** [comment]
MaxUsers isn't sent from login to channel, that's why it's 0.

**Comment by exectails** [comment]
Should be fixed now, post here if not.

This happened because a variable wasn't sent from the login server to the channels, which eventually resulted in a divide zero exception on the channel, when a player opened the channel selection.
