### ISSUE TITLE
Error in Partner Creation

### ISSUE THREAD

**Issue by ImaBrokeDude** [aura-project/aura#196]
One of my players tried creating the new partner that just came out, I am guessing there was a change in the packaets, idk if there is something new before `partner.Lower` but that is specifically the value that it crashes at!

```
1/6/2016 10:06:47 PM [Info] - User 'yumiser' logged in.
1/6/2016 10:10:33 PM [Info] - New character 'God' created in account 'yumiser'.
1/6/2016 10:11:10 PM [Error] - There has been a problem while handling '0045', 'CreatePartner'.
1/6/2016 10:11:10 PM [Exception] - System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Aura.Login.Database.Item.CardItemsToItems(IEnumerable`1 cardItems) in c:\Users\Administrator\Documents\Aura\aura\src\LoginServer\Database\Item.cs:line 62
   at Aura.Login.Database.Account.CreatePartner(Character partner) in c:\Users\Administrator\Documents\Aura\aura\src\LoginServer\Database\Account.cs:line 142
   at Aura.Login.Network.Handlers.LoginServerHandlers.CreatePartner(LoginClient client, Packet packet) in c:\Users\Administrator\Documents\Aura\aura\src\LoginServer\Network\Handlers\Creation.cs:line 408
   at Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet) in c:\Users\Administrator\Documents\Aura\aura\src\Shared\Network\PacketHandlerManager.cs:line 72
   at Aura.Shared.Network.DefaultServer`1.HandleBuffer(TClient client, Byte[] buffer) in c:\Users\Administrator\Documents\Aura\aura\src\Shared\Network\DefaultServer.cs:line 61
```

**Comment by ImaBrokeDude** [comment]
Ah I missed a line, might be a new item that ins't in the DB yet.
