### ISSUE TITLE
Exception When Completing Certain Quests

### ISSUE THREAD

**Issue by Yumiser** [aura-project/aura#328]
I am having issues with some quests throwing exceptions when trying to complete them. Players usually restart the client to correct the issue

```
2016-06-27 05:08 [Error] - There has been a problem while handling '8CA3', 'CompleteQuest'.
2016-06-27 05:08 [Exception] - System.ArgumentException: Quest '2020369' not found.
   at Aura.Channel.World.Entities.Item.CreateQuestScroll(Int32 questId)
   at Aura.Channel.World.Entities.Creatures.CreatureQuests.SendOwl(Int32 questId)
   at DuncansPraiseStarterScript.OnPlayerCompletesQuest(Creature creature, Int32 questId)
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at Aura.Channel.World.EventHandlerExtensions.Raise[T1,T2](Action`2 handler, T1 args1, T2 args2)
   at Aura.Channel.World.Entities.Creatures.CreatureQuests.Complete(Quest quest, Int32 rewardGroup, Boolean owl)
   at Aura.Channel.World.Entities.Creatures.CreatureQuests.Complete(Quest quest, Boolean owl)
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.CompleteQuest(ChannelClient client, Packet packet)
   at Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet)
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.Handle(ChannelClient client, Packet packet)
   at Aura.Shared.Network.DefaultServer`1.HandleBuffer(TClient client, Byte[] buffer)
```

**Comment by exectails** [comment]
Thanks for the report, there was a typo in the quest "Duncan's Praise", it should work from now on.
