### ISSUE TITLE
Character freeze @BossRoom

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#36]
https://youtu.be/pdqF9jhwvgg

Please ignore the music.

**Comment by DeleteIT** [comment]
Also, that golem doesn't maul you within the first 15 seconds? Aggro range is ***super*** incorrect.

**Comment by exectails** [comment]
Hm =< Any errors or debug messages in the log file?

**Comment by exectails** [comment]
Always take a look at the console/log file, to see if there's any indication of what the problem might be. Warnings, Errors, and Exceptions are usually a bad thing^^

```
10.09.2015 11:25:49 [Warning] - Unknown actor '#golem3'.
10.09.2015 11:25:50 [Error] - There has been a problem while handling '908B', 'TouchProp'.
10.09.2015 11:25:50 [Exception] - System.NullReferenceException: ...
```

**Comment by Pegwald** [comment]
Where can I find the log file? I like being useful :)

**Comment by exectails** [comment]
It's in the log folder inside your Aura folder.

**Comment by Pegwald** [comment]
Ah, there we go... I didn't find anything useful in that log. Can I paste it here anyways?

**Comment by exectails** [comment]
Nothing? Did you start the server again after the error? The log files in log/ are logs of the latest session, if you want to investigate earlier sessions you have to dig into the archive sub-folder.

**Comment by Pegwald** [comment]
Here's something I found:

"
10.09.2015 03:45:00 [Info] - Saved global script variables.
10.09.2015 03:49:18 [Debug] - Run locked for 'Peagon'.
10.09.2015 03:50:00 [Info] - Saved global script variables.
10.09.2015 03:55:00 [Info] - Saved global script variables.
10.09.2015 03:59:20 [Warning] - Unknown actor '#golem3'.
10.09.2015 03:59:20 [Error] - There has been a problem while handling '908B', 'TouchProp'.
10.09.2015 03:59:20 [Exception] - System.NullReferenceException: Object reference not set to an instance of an object.
   at Aura.Channel.World.Entities.NPC..ctor(ActorData actorData) in g:\Aura\aura\src\ChannelServer\World\Entities\NPC.cs:line 146
   at Aura.Channel.World.Cutscene.FromData(String name, Creature creature) in g:\Aura\aura\src\ChannelServer\World\Cutscene.cs:line 88
   at Aura.Channel.World.Cutscene.Play(String name, Creature creature) in g:\Aura\aura\src\ChannelServer\World\Cutscene.cs:line 181
   at Aura.Channel.World.Dungeons.Dungeon.PlayCutscene(String cutsceneName) in g:\Aura\aura\src\ChannelServer\World\Dungeons\Dungeon.cs:line 722
   at CiarIntOneDungeonScript.OnBoss(Dungeon dungeon) in c:\Users\Pegwald\AppData\Local\Temp\tmp3D2B.tmp:line 15
   at Aura.Channel.World.Dungeons.Dungeon.BossDoorBehavior(Creature _, Prop prop) in g:\Aura\aura\src\ChannelServer\World\Dungeons\Dungeon.cs:line 630
   at Aura.Channel.World.Entities.PropFunc.Invoke(Creature creature, Prop prop)
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.TouchProp(ChannelClient client, Packet packet) in g:\Aura\aura\src\ChannelServer\Network\Handlers\Props.cs:line 148
   at Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet) in g:\Aura\aura\src\Shared\Network\PacketHandlerManager.cs:line 70
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.Handle(ChannelClient client, Packet packet) in g:\Aura\aura\src\ChannelServer\Network\Handlers\Base.cs:line 58
   at Aura.Shared.Network.DefaultServer`1.HandleBuffer(TClient client, Byte[] buffer) in g:\Aura\aura\src\Shared\Network\DefaultServer.cs:line 67
10.09.2015 04:00:00 [Info] - Saved global script variables.
10.09.2015 04:01:26 [Info] - 'account_name' is closing the connection. Saving...
10.09.2015 04:01:26 [Info] - Connection closed from '127.0.0.1:65489.
10.09.2015 04:01:34 [Info] - Connection established from '127.0.0.1:59034.
10.09.2015 04:01:34 [Warning] - SwitchStatMods: Unknown title effect 'Crit' in title 10002.
10.09.2015 04:01:49 [Info] - 'account_name' is closing the connection. Saving...
10.09.2015 04:01:50 [Info] - Connection closed from '127.0.0.1:59034.
10.09.2015 04:05:00 [Info] - Saved global script variables.
10.09.2015 04:10:00 [Info] - Saved global script variables.
"

**Comment by exectails** [comment]
Yup, that's it^^ Because of the exception, your client never got a response it was waiting for, so it didn't allow you to do anything.

**Comment by Pegwald** [comment]
Ah I see. I can also enter the server again, it seems. You're great, man! :)
