### ISSUE TITLE
Channel server couldn't handle logging off, crashed whole server by force exitting.

### ISSUE THREAD

**Issue by samuelhamilton** [aura-project/aura#394]
Only happened once, was able to log off just fine before that. First time logging off outside of Tir Chonaill though.

`2016-08-26 12:24 [Info] - 'karavala' is closing the connection. Saving...
2016-08-26 12:24 [Error] - There has been a problem while handling '4E24', 'DisconnectRequest'.
2016-08-26 12:24 [Exception] - MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'NaN' in 'field list'
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Aura.Shared.Database.UpdateCommand.Execute() in C:\Users\dirkk_000\Documents\aura-project\trunk\src\Shared\Database\Commands.cs:line 98
   at Aura.Channel.Database.ChannelDb.SaveCharacter(PlayerCreature creature, Account account) in C:\Users\dirkk_000\Documents\aura-project\trunk\src\ChannelServer\Database\ChannelDb.cs:line 1081
   at Aura.Channel.Database.ChannelDb.SaveAccount(Account account) in C:\Users\dirkk_000\Documents\aura-project\trunk\src\ChannelServer\Database\ChannelDb.cs:line 992
   at Aura.Channel.Network.ChannelClient.CleanUp() in C:\Users\dirkk_000\Documents\aura-project\trunk\src\ChannelServer\Network\ChannelClient.cs:line 159
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.DisconnectRequest(ChannelClient client, Packet packet) in C:\Users\dirkk_000\Documents\aura-project\trunk\src\ChannelServer\Network\Handlers\LogInOut.cs:line 332
   at Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet) in C:\Users\dirkk_000\Documents\aura-project\trunk\src\Shared\Network\PacketHandlerManager.cs:line 72
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.Handle(ChannelClient client, Packet packet) in C:\Users\dirkk_000\Documents\aura-project\trunk\src\ChannelServer\Network\Handlers\Base.cs:line 58
   at Aura.Shared.Network.DefaultServer`1.HandleBuffer(TClient client, Byte[] buffer) in C:\Users\dirkk_000\Documents\aura-project\trunk\src\Shared\Network\DefaultServer.cs:line 67
2016-08-26 12:25 [Info] - Connection lost from '25.19.142.211:58890'.
2016-08-26 12:25 [Error] - Oh no! Ferghus escaped his memory block and infected the rest of the server!
2016-08-26 12:25 [Error] - Aura has encountered an unexpected and unrecoverable error. We're going to try to save as much as we can.
2016-08-26 12:25 [Exception] - System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
   at System.Threading.Timer.Change(Int32 dueTime, Int32 period)
   at Aura.Channel.World.Entities.Creatures.CreatureQuests.Dispose() in C:\Users\dirkk_000\Documents\aura-project\trunk\src\ChannelServer\World\Entities\Creatures\CreatureQuests.cs:line 55
   at Aura.Channel.World.Entities.Creature.Dispose() in C:\Users\dirkk_000\Documents\aura-project\trunk\src\ChannelServer\World\Entities\Creature.cs:line 1198
   at Aura.Channel.Network.ChannelClient.CleanUp() in C:\Users\dirkk_000\Documents\aura-project\trunk\src\ChannelServer\Network\ChannelClient.cs:line 114
   at Aura.Shared.Network.BaseClient.Kill() in C:\Users\dirkk_000\Documents\aura-project\trunk\src\Shared\Network\BaseClient.cs:line 117
   at Aura.Shared.Network.BaseServer`1.KillAndRemoveClient(TClient client) in C:\Users\dirkk_000\Documents\aura-project\trunk\src\Shared\Network\BaseServer.cs:line 228
   at Aura.Shared.Network.BaseServer`1.OnReceive(IAsyncResult result) in C:\Users\dirkk_000\Documents\aura-project\trunk\src\Shared\Network\BaseServer.cs:line 208
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
2016-08-26 12:25 [Status] - Closing server.
2016-08-26 12:25 [Info] - Exiting...`

**Comment by exectails** [comment]
Can you reliably reproduce this? Like, does it happen every time when you log out now? Can you tell me the version of you MySQL server?

NaN means "not a number" and is used for unrepresentable floats. There's either something wrong with MySQL or somehow one of the character's stats became NaN, and we have to figure out how and why. This might be tricky =/

**Comment by samuelhamilton** [comment]
I am using the XAMPP Control Panel's MySQL, which appears to be 10.1.13-MariaDB. I haven't been able to reproduce it yet, but I was messing with random items in the database that day, let me see if I can reproduce it.

**Comment by samuelhamilton** [comment]
I have not been able to reproduce the issue, after doing everything I could think of that I previously did. I will respond if it happens again.

**Comment by exectails** [comment]
Alright, I'll leave it open for the time being.

**Comment by exectails** [comment]
From the chat:

>@boilerplate5 23:51
uh
@exectails
![](http://puu.sh/r5H36/3d7713f27a.jpg)

>what happened to my stats
yep
That just did a thing
![](http://puu.sh/r5H7u/a6362e795d.png)

>I only just now noticed it.
._.
That was definitely something I ate
but no idea what
What...
Ch1 in maintenance now.
Well that was catastrophic.
Ok

>@boilerplate5 23:56
I don't know what it was, but something I ate out of the Boiling cooking tree annihilated my stats, soft locked the game, and put the server into a maintenance mode.
Ultra crash.
=|
I'm back in and all's fine but you get the idea.

@samuelhamilton Have you by any chance experimented with cooking as well?

**Comment by samuelhamilton** [comment]
Sorry it took me so long to respond, no, I had not done anything with cooking at the time.
