### ISSUE TITLE
Divide by 0 Exception

### ISSUE THREAD

**Issue by Xcelled** [aura-project/aura#93]
I just noticed it in my log. Seems like we might never actually set MaxUsers?

```
[Error] - There has been a problem while handling '4E34', 'GetChannelList'.
[Exception] - System.DivideByZeroException: Attempted to divide by zero.
   at Aura.Shared.Network.ChannelInfo.get_Stress() in D:\Documents\Programming\Visual Studio\Projects\aura\src\Shared\Network\ServerInfo.cs:line 62
   at Aura.Shared.Network.Sending.Helpers.ServerInfoHelper.AddChannelInfo(Packet packet, ChannelInfo channel, ServerInfoType type) in D:\Documents\Programming\Visual Studio\Projects\aura\src\Shared\Network\Sending\Helpers\ServerInfoHelper.cs:line 56
   at Aura.Shared.Network.Sending.Helpers.ServerInfoHelper.AddServerInfo(Packet packet, ServerInfo server, ServerInfoType type) in D:\Documents\Programming\Visual Studio\Projects\aura\src\Shared\Network\Sending\Helpers\ServerInfoHelper.cs:line 41
   at Aura.Channel.Network.Sending.Send.GetChannelListR(ChannelClient client, ServerInfo server) in D:\Documents\Programming\Visual Studio\Projects\aura\src\ChannelServer\Network\Sending\Send.LogInOut.cs:line 117
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.GetChannelList(ChannelClient client, Packet packet) in D:\Documents\Programming\Visual Studio\Projects\aura\src\ChannelServer\Network\Handlers\LogInOut.cs:line 320
   at Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet) in D:\Documents\Programming\Visual Studio\Projects\aura\src\Shared\Network\PacketHandlerManager.cs:line 70
   at Aura.Channel.Network.Handlers.ChannelServerHandlers.Handle(ChannelClient client, Packet packet) in D:\Documents\Programming\Visual Studio\Projects\aura\src\ChannelServer\Network\Handlers\Base.cs:line 58
   at Aura.Shared.Network.DefaultServer`1.HandleBuffer(TClient client, Byte[] buffer) in D:\Documents\Programming\Visual Studio\Projects\aura\src\Shared\Network\DefaultServer.cs:line 67
```

**Comment by exectails** [comment]
We are setting max users, question is, why did you set the max users to 0?

**Comment by Xcelled** [comment]
For the record: I didn't :c

**Comment by exectails** [comment]
How did it happen then? =<

**Comment by Xcelled** [comment]
I have legit no idea. I checked the conf and it was still 20. Gremlin?
